version: "3.9"

services:
  prepare_params:
    build: "."
    image: adafede/tima-r
    volumes:
      - "./params:/params"
    command: Rscript inst/scripts/prepare_params.R

  tests:
    build: "."
    image: adafede/tima-r
    volumes:
      - "./params:/params"
      - "./inst:/inst"
      - "./data:/data"
    command: Rscript inst/scripts/tima_mini.R

  tima:
    build: "."
    image: adafede/tima-r
    volumes:
      - "./params:/params"
      - "./inst:/inst"
      - "./data:/data"
    command: Rscript inst/scripts/tima_full.R

# other smaller services not implemented yet