version: "3.9"

services:
  tima-full:
    build: "."
    image: adafede/tima-r
    volumes:
      - "./params:/params"
      - "./inst:/inst"
      - "./data:/data"
    command: Rscript inst/scripts/tima_full.R

  tima-gui:
    build: "."
    ports:
      - "3838:3838"
    image: adafede/tima-r
    volumes:
      - "./params:/params"
      - "./inst:/inst"
      - "./data:/data"
    command: Rscript -e "shiny::runApp(appDir = 'inst/app', host = '0.0.0.0', port = 3838)"

  tima-mini:
    build: "."
    image: adafede/tima-r
    volumes:
      - "./params:/params"
      - "./inst:/inst"
      - "./data:/data"
    command: Rscript inst/scripts/tima_mini.R
