version: "3.9"

services:
  tima-full:
    build: "."
    image: adafede/tima-r
    volumes:
      - "./params:/params"
      - "./inst:/inst"
      - "./data:/data"
    command: Rscript inst/scripts/tima_full.R

  tima-gui:
    build: "."
    image: adafede/tima-r
    volumes:
      - "./params:/params"
    command: Rscript inst/app/app.R

  tima-mini:
    build: "."
    image: adafede/tima-r
    volumes:
      - "./params:/params"
      - "./inst:/inst"
      - "./data:/data"
    command: Rscript inst/scripts/tima_mini.R
