version: "3.9"

services:
  tima-full:
    build: "."
    image: adafede/tima-r
    volumes:
      - "./params:/params"
      - "./inst:/inst"
      - "./data:/data"
    command: Rscript inst/scripts/tima_full.R

  tima-gui:
    build: "."
    ports:
      - "3838:3838"
      - "3839:3839"
    image: adafede/tima-r
    volumes:
      - "./params:/params"
      - "./inst:/inst"
      - "./data:/data"
    command: Rscript inst/scripts/run_app.R

  tima-mini:
    build: "."
    image: adafede/tima-r
    volumes:
      - "./params:/params"
      - "./inst:/inst"
      - "./data:/data"
    command: Rscript inst/scripts/tima_mini.R
