---
services:
  tima-full:
    build: "."
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 8G
    healthcheck:
      test: ["NONE"]
      interval: 200s
      timeout: 200s
      retries: 5
    image: adafede/tima-r
    networks:
      - service-service-frontend
    security_opt:
      - apparmor:unconfined
      - no-new-privileges:true
    user: tima-user
    volumes:
      - "./data:/home/tima-user/data"
    command: Rscript -e "targets::tar_make(names = matches("^ann_pre$"), script=system.file("pipelines/_targets.R", package = "tima"))"

  tima-gui:
    build: "."
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: 8G
    healthcheck:
      test: ["NONE"]
      interval: 200s
      timeout: 200s
      retries: 5
    ports:
      - "3838:3838"
      - "3839:3839"
    image: adafede/tima-r
    networks:
      - service-service-frontend
    security_opt:
      - apparmor:unconfined
      - no-new-privileges:true
    user: tima-user
    volumes:
      - "./data:/home/tima-user/data"
    command: Rscript -e "tima::run_app()"

networks:
  service-service-frontend:
