export CONFIG_DEFAULT_PATH = ${CONFIG_PATH}/default
export CONFIG_PARAMS_PATH = ${CONFIG_PATH}/params

export DATA_INTERIM_PATH = ${DATA_PATH}/interim
export DATA_PROCESSED_PATH = ${DATA_PATH}/processed
export DATA_SOURCE_PATH = ${DATA_PATH}/source

export DATA_INTERIM_ADDUCTS_PATH = ${DATA_INTERIM_PATH}/adducts
export DATA_INTERIM_ANNOTATIONS_PATH = ${DATA_INTERIM_PATH}/annotations
export DATA_INTERIM_CONFIG_PATH = ${DATA_INTERIM_PATH}/config
export DATA_INTERIM_EDGES_PATH = ${DATA_INTERIM_PATH}/edges
export DATA_INTERIM_LIBRARIES_PATH = ${DATA_INTERIM_PATH}/libraries
export DATA_INTERIM_TAXA_PATH = ${DATA_INTERIM_PATH}/taxa

export DATA_SOURCE_DICTIONARIES_PATH = ${DATA_SOURCE_PATH}/dictionaries
export DATA_SOURCE_LIBRARIES_PATH = ${DATA_SOURCE_PATH}/libraries

export SRC_DOCOPT_PATH = ${SRC_PATH}/docopt
export SRC_R_PATH = ${SRC_PATH}/R
