#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(tima)
})

write_tables_json <- function(input_file, output_file) {
  read_tables <- getFromNamespace("read_mztab_tables", "tima")
  tabs <- read_tables(input_file)
  payload <- list(
    source = normalizePath(input_file, winslash = "/", mustWork = FALSE),
    metadata = as.data.frame(tabs$metadata, stringsAsFactors = FALSE),
    sml = as.data.frame(tabs$sml, stringsAsFactors = FALSE),
    smf = as.data.frame(tabs$smf, stringsAsFactors = FALSE),
    sme = as.data.frame(tabs$sme, stringsAsFactors = FALSE)
  )
  jsonlite::write_json(
    payload,
    path = output_file,
    auto_unbox = TRUE,
    pretty = TRUE,
    na = "null"
  )
  output_file
}

# Prefer local source code when running from the repository checkout.
if (
  file.exists("DESCRIPTION") && requireNamespace("devtools", quietly = TRUE)
) {
  desc_lines <- readLines("DESCRIPTION", warn = FALSE)
  if (any(grepl("^Package:\\s*tima\\s*$", desc_lines))) {
    suppressMessages(devtools::load_all(".", quiet = TRUE))
  }
}

args <- commandArgs(trailingOnly = TRUE)

get_arg <- function(flag, default = NULL) {
  i <- match(flag, args)
  if (is.na(i) || i == length(args)) {
    return(default)
  }
  args[[i + 1L]]
}

fixtures_dir <- get_arg("--fixtures-dir", "tests/testthat/fixtures/mztab")
out_dir <- get_arg(
  "--output-dir",
  file.path(tempdir(), "tima_mztab_before_after")
)
str_stereo <- get_arg(
  "--str-stereo",
  "tests/testthat/fixtures/structures_stereo.csv"
)
str_met <- get_arg(
  "--str-met",
  "tests/testthat/fixtures/structures_metadata.csv"
)
str_tax_cla <- get_arg(
  "--str-tax-cla",
  "tests/testthat/fixtures/structures_taxonomy_cla.csv"
)
str_tax_npc <- get_arg(
  "--str-tax-npc",
  "tests/testthat/fixtures/structures_taxonomy_npc.csv"
)

if (!dir.exists(fixtures_dir)) {
  stop("fixtures directory not found: ", fixtures_dir)
}

mztab_files <- list.files(
  fixtures_dir,
  pattern = "\\.(mztab|mzTab|json)$",
  full.names = TRUE,
  ignore.case = TRUE
)

if (length(mztab_files) == 0L) {
  stop("no mzTab fixtures found in: ", fixtures_dir)
}

dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

manifest <- vector("list", length(mztab_files))

for (i in seq_along(mztab_files)) {
  in_file <- mztab_files[[i]]
  id <- tools::file_path_sans_ext(basename(in_file))
  dir_i <- file.path(out_dir, id)
  dir.create(dir_i, recursive = TRUE, showWarnings = FALSE)

  before_json <- file.path(dir_i, "before_tables.json")
  after_json <- file.path(dir_i, "after_tables.json")
  input_ext <- tolower(tools::file_ext(in_file))
  input_copy <- file.path(
    dir_i,
    paste0("before", if (nzchar(input_ext)) paste0(".", input_ext) else "")
  )
  file.copy(in_file, input_copy, overwrite = TRUE)

  before_features <- file.path(dir_i, "before_features.tsv")
  before_spectra <- file.path(dir_i, "before_spectra.mgf")
  before_metadata <- file.path(dir_i, "before_metadata.tsv")
  ann_tsv <- file.path(dir_i, "tima_annotations.tsv")
  after_mztab <- file.path(dir_i, "after_tima.mztab")
  after_features <- file.path(dir_i, "after_features.tsv")
  after_spectra <- file.path(dir_i, "after_spectra.mgf")
  after_metadata <- file.path(dir_i, "after_metadata.tsv")

  status <- "ok"
  err_msg <- ""

  tryCatch(
    {
      # Extract what TIMA can consume directly from the original fixture.
      read_mztab(
        input = in_file,
        output_features = before_features,
        output_spectra = before_spectra,
        output_metadata = before_metadata
      )
      write_tables_json(in_file, before_json)

      # Build TIMA annotation table from fixture then complement original mzTab.
      prepare_annotations_mztab(
        input = in_file,
        output = ann_tsv,
        str_stereo = str_stereo,
        str_met = str_met,
        str_tax_cla = str_tax_cla,
        str_tax_npc = str_tax_npc
      )

      is_json_input <- grepl("\\.json$", in_file, ignore.case = TRUE)
      write_args <- list(
        input = ann_tsv,
        output = after_mztab,
        title = paste("TIMA complemented:", basename(in_file)),
        description = "Generated by mztab_before_after_batch.R"
      )
      if (!is_json_input) {
        write_args$base_mztab <- in_file
      }
      do.call(write_mztab, write_args)

      # Extract again from complemented mzTab for quick diffing.
      read_mztab(
        input = after_mztab,
        output_features = after_features,
        output_spectra = after_spectra,
        output_metadata = after_metadata
      )
      write_tables_json(after_mztab, after_json)
    },
    error = function(e) {
      status <<- "error"
      err_msg <<- conditionMessage(e)
    }
  )

  before_rows <- if (file.exists(before_features)) {
    nrow(tidytable::fread(before_features))
  } else {
    NA_integer_
  }
  after_rows <- if (file.exists(after_features)) {
    nrow(tidytable::fread(after_features))
  } else {
    NA_integer_
  }

  manifest[[i]] <- data.frame(
    fixture = basename(in_file),
    fixture_path = normalizePath(in_file, winslash = "/", mustWork = FALSE),
    status = status,
    error = err_msg,
    before_input_copy = input_copy,
    before_tables_json = before_json,
    after_mztab = after_mztab,
    after_tables_json = after_json,
    before_features = before_features,
    before_spectra = before_spectra,
    before_metadata = before_metadata,
    after_features = after_features,
    after_spectra = after_spectra,
    after_metadata = after_metadata,
    before_features_rows = before_rows,
    after_features_rows = after_rows,
    stringsAsFactors = FALSE
  )

  message(
    "[",
    i,
    "/",
    length(mztab_files),
    "] ",
    basename(in_file),
    " -> ",
    dir_i
  )
}

manifest_df <- do.call(rbind, manifest)
manifest_path <- file.path(out_dir, "manifest.csv")
write.csv(manifest_df, manifest_path, row.names = FALSE)
manifest_json_path <- file.path(out_dir, "manifest.json")
jsonlite::write_json(
  manifest_df,
  path = manifest_json_path,
  auto_unbox = TRUE,
  pretty = TRUE,
  na = "null"
)

message("Done. Outputs in: ", out_dir)
message("Manifest: ", manifest_path)
message("Manifest JSON: ", manifest_json_path)
