---
title: "0 General comments about the infrastructure"
author: "Adriano Rutz"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{0 General comments about the infrastructure}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette describes the philosophy behind the infrastructure of **TIMA**.

It is currently under construction. 

## Philosophy

Our main goals were **flexibility** and **reproducibility**. 

### Flexibility

To ensure flexibility, we tried to split the process in as much tiny parts as needed.
So you can decide whether to skip an optional part, add your own processing, etc.
We tried to cover most use cases, but of course they are not exhaustive. 
If you feel like something useful to other users is missing, please fill an [issue](https://github.com/taxonomicallyinformedannotation/tima-r/issues).

### Reproducibility

After some time using TIMA, you will probably wonder: 
"*What was the parameters I used to generate this file?*" ...
Or a collaborator might ask you to share your data and parameters.
Writing them down each time might be time consuming and not really in line with modern computational approaches.
Therefore, we chose to implement all parameters of all steps (almost...) as YAML files.
They are human-readable and can be used in batches.
If you do not like YAML, parameters of each steps can also be given as command line arguments.
They will then be saved as YAML you will be able to share.

## Use

Under construction
Until it is finished, here are the most relevant commands

### Copy initial parameters

As mentioned previously, scripts need some parameters to be filled.
Some pre-defined parameters are given in `config/default` directory.
Those will help you understanding how the workflow works so you can adapt them later to your own data.
So first, start by copying them into `config/params` directory.
To do so:

```shell
# copy the default params to adapat to your data later on
cp -R config/default config/params
```

You now have all parameters copied in `config/params` directory, so you can start modifying them according to your own data.

### Structure-organism pairs library

The first pre-requisite to perform *taxonomically informed metabolite annotation* is to have a *structure-organism pairs* library.

#### LOTUS

As starting point, we provide **LOTUS**.
To download LOTUS pairs locally, and format them to further use, do:

```shell
Rscript inst/scripts/get_lotus.R
Rscript inst/scripts/prepare_lotus.R
```

More details can be found ... TODO

#### Other libraries

As we want our tool to be flexible, you can also add your own library to LOTUS.
You just need to format it in order to be compatible.
As example, we prepared some ways too format closed, *in house* libraries.
If you need help formatting your library or would like to share it with us for it to be implemented, feel free to contact us.

```shell
Rscript inst/scripts/prepare_closed.R # only if you have access to it
```

#### Merging

Once you have all your sub-libraries prepared, you are ready to merge them in a single file that will be used for coming steps.
An adduct library will also be generated in order to perform MS1 annotation later on.

```shell
Rscript inst/scripts/prepare_library.R
Rscript inst/scripts/prepare_adducts.R
```

### Annotations

#### Get MS2 annotations

Get an example result from [spectral_lib_matcher](https://github.com/mandelbrot-project/spectral_lib_matcher), which is only in python. see related repo)
For the moment, we provide an example file coming from the new ISDB.
We are working on a better integration.
It also supports annotations coming from GNPS (see next steps).

```shell
Rscript inst/scripts/get_example_isdb.R
```

#### Format MS2 annotations

depending on the annotation tool you used

```shell
Rscript inst/scripts/prepare_gnps.R # optional
Rscript inst/scripts/prepare_sirius.R # optional
Rscript inst/scripts/prepare_isdb.R
```

#### Complement MS2 annotations (with spectral clusters and chemical taxonomy of annotations)

```shell
Rscript inst/scripts/prepare_edges.R
Rscript inst/scripts/prepare_features_components.R
Rscript inst/scripts/prepare_features_classification.R
```

#### Get biological taxonomy information

```shell
Rscript inst/scripts/prepare_taxa.R
```

### And finally the graal!

```shell
Rscript inst/scripts/process_annotations.R
```

NOTE: you can use --help or -h argument for all .R steps to get more info

Rest to come ...
