# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
DISABLE_ERRORS_LINTERS:
  - COPYPASTE_JSCPD
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - R_LINTR
  - REPOSITORY_CHECKOV
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - REPOSITORY_TRIVY
DISABLE_LINTERS:
  - SPELL_CSPELL
  - SPELL_LYCHEE
MARKDOWN_FILTER_REGEX_EXCLUDE: '(LICENSE\.md|NEWS\.md|.*\.json|inst/app/tests/shinytest/test_app-expected/.*\.json)'
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
PRE_COMMANDS:
  - command: R --slave -e 'install.packages(c("lintr"))'
    cwd: "root"
