#' @title Change Params Small
#'
#' @description This function helps changing convenience parameters.
#'
#' @include create_dir.R
#' @include get_default_paths.R
#' @include go_to_cache.R
#' @include load_yaml_files.R
#'
#' @param fil_pat The pattern identifying your whole job. You can put whatever you want. STRING
#' @param fil_fea_raw The path to the file containing your features' intensities. Can be generated by mzmine, SLAW, or SIRIUS. STRING
#' @param fil_met_raw The path to the file containing your metadata. If your experiment contains a single taxon, you can provide it below instead. STRING
#' @param fil_sir_raw The directory containing the sirius annotations. STRING
#' @param fil_spe_raw The path to the file containing your features' spectra. Can contain MS1 and/or MS2 spectra. STRING
#' @param ms_pol The polarity used. Must be either "pos" or "neg". STRING
#' @param org_tax If your experiment contains a single taxon, its scientific name. "Homo sapiens". STRING
#' @param hig_con Filter high confidence candidates only. BOOLEAN
#' @param summarize Summarize all candidates per feature to a single row. BOOLEAN
#'
#' @export
#'
#' @return YAML file with changed parameters.
#'
#' @examples
#' \dontrun{
#' copy_backbone()
#' tima::change_params_small(
#'   fil_pat = "myExamplePattern",
#'   fil_fea_raw = "myExampleDir/myExampleFeatures.csv",
#'   fil_met_raw = "myExampleDir2SomeWhereElse/myOptionalMetadata.tsv",
#'   fil_sir_raw = "myExampleDir3/myAwesomeSiriusProject.zip",
#'   fil_spe_raw = "myBeautifulSpectra.mgf",
#'   ms_pol = "pos",
#'   org_tax = "Gentiana lutea",
#'   hig_con = TRUE,
#'   summarize = FALSE
#' )
#' }
change_params_small <- function(
  fil_pat = NULL,
  fil_fea_raw = NULL,
  fil_met_raw = NULL,
  fil_sir_raw = NULL,
  fil_spe_raw = NULL,
  ms_pol = NULL,
  org_tax = NULL,
  hig_con = NULL,
  summarize = NULL
) {
  go_to_cache()
  paths_data_source <- get_default_paths()$data$source$path
  paths_data_interim_annotations <-
    get_default_paths()$data$interim$annotations$path
  create_dir(paths_data_source)
  list <- load_yaml_files()

  yamls_params <- list$yamls_params

  yaml_small <- yamls_params[["params/prepare_params"]]
  if (!is.null(fil_pat)) {
    yaml_small$files$pattern <- fil_pat
  }
  if (!is.null(fil_fea_raw)) {
    stopifnot("Your features' file does not exist" = file.exists(fil_fea_raw))
    fil_fea_raw_rdy <- paths_data_source |>
      file.path(basename(fil_fea_raw))
    fs::file_copy(
      path = fil_fea_raw,
      new_path = fil_fea_raw_rdy,
      overwrite = TRUE
    )
    yaml_small$files$features$raw <- fil_fea_raw_rdy
  }
  if (!is.null(fil_met_raw)) {
    stopifnot("Your metadata file does not exist" = file.exists(fil_met_raw))
    fil_met_raw_rdy <- paths_data_source |>
      file.path(basename(fil_met_raw))
    fs::file_copy(
      path = fil_met_raw,
      new_path = fil_met_raw_rdy,
      overwrite = TRUE
    )
    yaml_small$files$metadata$raw <- fil_met_raw_rdy
  }
  if (!is.null(fil_sir_raw)) {
    stopifnot("Your sirius directory does not exist" = file.exists(fil_sir_raw))
    fil_sir_raw_rdy <- paths_data_interim_annotations |>
      file.path(basename(fil_sir_raw))
    fs::file_copy(
      path = fil_sir_raw,
      new_path = fil_sir_raw_rdy,
      overwrite = TRUE
    )
    yaml_small$files$annotations$raw$sirius <- fil_sir_raw_rdy
  } else {
    yaml_small$files$annotations$raw$sirius <- NA
  }
  if (!is.null(fil_spe_raw)) {
    stopifnot("Your spectra file does not exist" = file.exists(fil_spe_raw))
    fil_spe_raw_rdy <- paths_data_source |>
      file.path(basename(fil_spe_raw))
    fs::file_copy(
      path = fil_spe_raw,
      new_path = fil_spe_raw_rdy,
      overwrite = TRUE
    )
    yaml_small$files$spectral$raw <- fil_spe_raw_rdy
  }
  if (!is.null(ms_pol)) {
    yaml_small$ms$polarity <- ms_pol
  }
  if (!is.null(org_tax)) {
    yaml_small$organisms$taxon <- org_tax
  } else {
    yaml_small$organisms$taxon <- NA
  }
  if (!is.null(hig_con)) {
    yaml_small$options$high_confidence <- hig_con
  }
  if (!is.null(summarize)) {
    yaml_small$options$summarize <- summarize
  }

  ## Dirty way to write null in the yaml
  null_handler <- function(x) {
    if (!is.na(x)) {
      return(x)
    }
    res <- "null"
    class(res) <- "verbatim"
    return(res)
  }
  yaml::write_yaml(
    x = yaml_small,
    file = get_default_paths()$params$prepare_params,
    handlers = list(logical = null_handler)
  )
}
