# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gnps_cpp <- function(x, y) {
  .Call(`_tima_gnps_cpp`, x, y)
}

join_gnps_cpp <- function(x, y, xPrecursorMz = NA_real_, yPrecursorMz = NA_real_, tolerance = 0, ppm = 0) {
  .Call(`_tima_join_gnps_cpp`, x, y, xPrecursorMz, yPrecursorMz, tolerance, ppm)
}
