---
name: External Use
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch: null
permissions: read-all
jobs:
  tima-test:
    name: tima-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@97330871fe1b7d3529392ea000e3d2c4b357e403
        id: cpu-cores
      - uses: r-lib/actions/setup-r@a51a8012b0aab7c32ef9d19bf54da93f3254335e
        with:
          use-public-rspm: true
          Ncpus: ${{ steps.cpu-cores.outputs.count }}
      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: >
          sudo apt-get update && sudo apt-get install -y --no-install-recommends
          libarchive-dev libcurl4-openssl-dev libfribidi-dev libharfbuzz-dev libuv1-dev \

          && sudo apt-get clean \

          && sudo rm -rf /var/lib/apt/lists/*
      - name: Install
        run: >
          install.packages(
          "tima",
          repos = c(
          "https://taxonomicallyinformedannotation.r-universe.dev",
          "https://bioconductor.org/packages/release/bioc",
          "https://cloud.r-project.org"
          )
          )

          tima::install_tima()
        shell: Rscript {0}
      - name: Get example files
        run: |
          tima::get_example_files()
        shell: Rscript {0}
      - name: Run pipeline
        run: |
          tima::run_tima()
          # Check if targets works correctly
          tima::run_tima()
        shell: Rscript {0}
