---
name: External Use
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch: null
permissions: read-all
jobs:
  tima-test:
    name: tima-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: r-lib/actions/setup-r@d3c5be51b12e724e68f33216ca3c148b66d5f0b6
        with:
          update-rtools: true

      - name: Install dependencies (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            libarchive-dev libcurl4-openssl-dev libfribidi-dev libharfbuzz-dev \
            libssl-dev libuv1-dev pkg-config \
          && sudo apt-get clean \
          && sudo rm -rf /var/lib/apt/lists/*

      - name: Install dependencies (macOS)
        if: contains(matrix.os, 'macos')
        run: |
          brew update
          brew install libomp
          GETTEXT_PREFIX="$(brew --prefix gettext)"
          LIBOMP_PREFIX="$(brew --prefix libomp)"

      - name: Install dependencies (Windows)
        if: contains(matrix.os, 'windows')
        run: true

      - name: Install
        run: >
          install.packages(
          "tima",
          repos = c(
          "https://taxonomicallyinformedannotation.r-universe.dev",
          "https://cran.r-universe.dev",
          "https://bioc.r-universe.dev"
          )
          )

          tima::install_tima()
        shell: Rscript {0}

      - name: Get example files
        run: |
          tima::get_example_files()
        shell: Rscript {0}

      - name: Run pipeline
        run: |
          tima::run_tima()
          # Check if targets works correctly
          tima::run_tima()
        shell: Rscript {0}
