---
name: License Report

permissions: read-all

on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  license-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - name: License Report
        uses: insightsengineering/r-license-report@6b011d92e042fb70b5670a49021d397fd9f1ee4e
