---
name: License Report

permissions: read-all

on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  license-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: License Report
        uses: insightsengineering/r-license-report@v1
